### ISSUE TITLE
Add plot for sequence length distribution

### ISSUE THREAD

**Issue by edgardomortiz** [UofABioinformaticsHub/ngsReports#17]
Thank you very much for developing this package, is really useful. The only thing missing from the FASTQC reports is the sequence length distribution, which I usually compare between raw sequence and quality trimmed fastqs. Would it be possible to implement?

Edgardo.

**Comment by steveped** [comment]
Hi Edgardo,
Thanks for the kind words & I'm really glad your'e finding it useful. I find myself using it most days as well. There is a function `plotSeqLengthDistn()` which you would call using `plotSeqLengthDistn(fdl)` or  `plotSeqLengthDistn(fdl, plotType = "line")`. Is that what you're looking for, or is there something else you were thinking of?
Steve

**Comment by edgardomortiz** [comment]
Dear Steve,
Thanks a lot, that is what I was looking for, I overlooked it because I was following the vignette only. I am attaching the type of report I want to get. Everything is fine except that I would also like to have both graphs for `Per base sequence content` with the samples in the same order. Any tip to accomplish that?
Edgardo
[paepalanthus_qc.31082019.html.zip](https://github.com/UofABioinformaticsHub/ngsReports/files/3563685/paepalanthus_qc.31082019.html.zip)

**Comment by steveped** [comment]
Hi Edgardo,
Nice one. That's a great report! I've wanted to make one up exactly like that for ages but haven't had the time to dig deeply enough with any datasets lately. 
As to the re-ordering in `plotSeqContent()`, I think the issues have come with the defaults for the `cluster` and `dendrogram` arguments. If you added `cluster = FALSE, dendrogram = FALSE` to your call, does it fix it? We have them set as `FALSE` by default for all other plots, but for some reason it looks like they're set as `TRUE` by default for this one. We'll have to change that for more consistent behaviour in the next Bioc release. The dendrograms only appear when setting `usePlotly = TRUE` so I think that's why we didn't notice.
Cheers,
Steve

**Comment by edgardomortiz** [comment]
Perfect, `cluster=FALSE, dendrogram=FALSE` fixed the order of the samples. Thanks for the help.

Best,
Edgardo
