### ISSUE TITLE
generating report failed

### ISSUE THREAD

**Issue by lmanchon** [UofABioinformaticsHub/ngsReports#8]
--Hi,

i use ngsReports (Bioc3.6) and i try to generate report from FastQC directory with:

library(ngsReports)
writeHtmlReport("./QC")
FastQC files found. Loading FastQC data
Checking for targets.csv
targets.csv not found. Using default labels
Quitting from lines 167-184 (ngsReports_Fastqc.Rmd)
Error in if (nrow(os) > 0) { : the argument is of null length

what's wrong ?

thank you --

**Comment by steveped** [comment]
Hi.

Sorry this is a bug that's been fixed in the later versions of the package. It just means that you have no Over-represented Sequences. Just open the Rmd document that's been dropped in the folder with your FastQC files in RStudio and set `eval = FALSE` for this chunk. The Kmer Content chunk may also need changing using `eval = FALSE`. You can then just click the `Knit` button and it should work

Cheers

**Comment by lmanchon** [comment]
in this way ? :

```{r Overrepresented_sequences, echo=FALSE, results='asis', message=TRUE, eval=FALSE}

```{r Kmer_Content, message=TRUE, eval=FALSE}

**Comment by steveped** [comment]
Yes. Perfect!

**Comment by lmanchon** [comment]
ok, good. It works fine !
thank you so much.

**Comment by steveped** [comment]
Great. Glad we got it sorted for you. BioC is up to 3.8 now so we've left this branch frozen. We'll merge the `dev` branch with master soon ready for 3.8 too. No new features but LOTS of bug fixes.
